### ISSUE TITLE
Populate PLATFORM_* environment variables: ./drush/platformsh_generate_drush_yml.php fails in ddev

### ISSUE THREAD

**Issue by rfay** [platformsh/ddev-platformsh#15]
`php ./drush/platformsh_generate_drush_yml.php` (hook provided by drupal template) fails with "failed to find a site URL" on ddev.

**Comment by rfay** [comment]
This is a result of the environment variable PLATFORM_APPLICATION_NAME being missing, so will be fixed with populating `PLATFORM_*` environment variables.

**Comment by lolautruche** [comment]
Mmm it's from the ConfigReader which is used in the Drupal template...

**Comment by lolautruche** [comment]
Re `$PLATFORM_ROUTES`, here's what I have in my Symfony app on a PSH environment:

```json
{
  "https://workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/": {
    "primary": true,
    "id": null,
    "production_url": "https://workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/",
    "attributes": {},
    "type": "upstream",
    "upstream": "app",
    "original_url": "https://{default}/"
  },
  "https://www.workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/": {
    "primary": false,
    "id": null,
    "production_url": "https://www.workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/",
    "attributes": {},
    "type": "redirect",
    "to": "https://workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/",
    "original_url": "https://www.{default}/"
  },
  "http://workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/": {
    "original_url": "http://{default}/",
    "id": null,
    "primary": false,
    "type": "redirect",
    "to": "https://workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/",
    "production_url": "http://workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/"
  },
  "http://www.workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/": {
    "original_url": "http://www.{default}/",
    "id": null,
    "primary": false,
    "type": "redirect",
    "to": "https://www.workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/",
    "production_url": "http://www.workshop-5ziq2gq-6j4ypl5iendqc.eu-3.platformsh.site/"
  }
}
```

**Comment by lolautruche** [comment]
I guess it should be easy to populate this `$PLATFORM_ROUTES` env var based on the URL generated by DDEV:

```json
{
  "https://bigfoot-symfony.ddev.site/": {
    "primary": true,
    "id": null,
    "production_url": "https://bigfoot-symfony.ddev.site/",
    "attributes": {},
    "type": "upstream",
    "upstream": "app",
    "original_url": "https://{default}/"
  }
}
```

This value would then be base64 encoded and assigned to `$PLATFORM_ROUTES`

**Comment by lolautruche** [comment]
PSH docs only explains that some variables like `PLATFORM_ROUTES` are base64-encoded JSON objects.
So assuming that you have the JSON example above in a `routes.json` file, you can obtain the base64 blob by doing:

```
cat routes.json | base64
```

**Comment by rfay** [comment]
Of course... we can't assume that the base64 tool is available on the host, so there will be some issues here.

**Comment by lolautruche** [comment]
Could this be done using Go somehow?

**Comment by rfay** [comment]
Of course, but the go code doesn't know we're doing platformsh stuff. Will have to think how it could be informed or triggered. 

This whole class of things is going to turn out to be fragile and not completely solvable.
