### ISSUE TITLE
Handle build, deploy, and post-deploy hooks

### ISSUE THREAD

**Issue by rfay** [platformsh/ddev-platformsh#16]
I hadn't been exposed to anything but deploy hooks, but there are also build and post-deploy hooks, docs at https://docs.platform.sh/create-apps/hooks/hooks-comparison.html

It would be nicer if each upstream hook was a separate item instead of how they're currently all bundled together.

**Comment by lolautruche** [comment]
I gave you access to the "BigFoot Symfony" project that I was using.
You can also use the official Symfony one (you may use the "Deploy on Platform.sh button").
