### ISSUE TITLE
Experiment with "wordpress-performance" build

### ISSUE THREAD

**Issue by rfay** [platformsh/ddev-platformsh#18]
@lolautruche mentions that this repo would be a good one for experimentation with this add-on:
https://github.com/platformsh/wordpress-performance

**Comment by gilzow** [comment]
**Please** don't use this repository for testing. It's not a normal platform project build and was created for use with the WordPress core team for a very specific purpose.

**Comment by rfay** [comment]
OK, we have way plenty of fish to fry :)
