### ISSUE TITLE
Delegate Platform.sh hosting provider to the add-on

### ISSUE THREAD

**Issue by lolautruche** [platformsh/ddev-platformsh#2]
DDEV provides a [hosting provider config for Platform.sh](https://ddev.readthedocs.io/en/stable/users/providers/platform/).

This should be delegated to the add-on, with additional features:
* Interactive setup (See #3 )
  * [CLI Token](https://docs.platform.sh/development/cli/api-tokens.html), with choice to store it globally (default) or at project level. Discard if already set
  * Project ID, unless the local project is already configured (`platform project:info id`)
  * Default environment (`platform project:info default_branch`)
  * Possible to cancel and re-run the setup later
  * Choice to pull the database and mounts from PSH, based on the current environment
    * `platform env` / `platform environment:info id`

**Comment by rfay** [comment]
#10 provides interactive request for the CLI token at this time.
