### ISSUE TITLE
`platform-setup` Go app

### ISSUE THREAD

**Issue by lolautruche** [platformsh/ddev-platformsh#3]
The `platform-setup` app would host most of the setup commands needed for the add-on.
Usage of Go is justified by the fact of staying OS agnostic (especially working on Windows).

## Examples of commands
* `platform-setup init` (for [base interactive setup](#2))
* `platform-setup config` (generate DDEV config out of Platform config

**Comment by rfay** [comment]
This issue needs more detail. What are we going to set up? What would be some example use-cases (in detail). Thanks!

**Comment by rfay** [comment]
With #10 I think DDEV now knows how to do "all the things" itself. It may or may not be more robust than what's envisioned here.
