### ISSUE TITLE
platform self-update on dockerfile will be cached?

### ISSUE THREAD

**Issue by hanoii** [platformsh/ddev-platformsh#31]
I was just thinking about this on a platform project I am working on (I don't use the full addon) but I was annoying at always getting the update notification.

My not so important concern here is that the RUN command will be cached, so eventually you'll get again the same behavior as using the standard ddev image.

I thought different ways of adding it to the Dockerfile, the most obvious one being downloading a specific version phar that you'll have to update everytime there's a new version, probably too annoying.

In the end I added as a post-start hook. I know it will run every start, but I rather live with that. Just sharing this thought for you to consider.

**Comment by rfay** [comment]
Thanks, and glad you're using some parts. I didn't quite understand what update notification you were talking about?

**Comment by rfay** [comment]
Oh you're saying that the platform tool inside is wanting the self-update when you use it. Yeah, it only gets done the one time during build, but the build cache in Docker then doesn't try it again :( 

IMO it would be best to disable that.

**Comment by hanoii** [comment]
the auto add to start could be the hook, you could add a config.platformsh.yml with a post-start hook, although you'll have to add it to the git repo as well as a post_install action as it will otherwise be ignored.

**Comment by hanoii** [comment]
```yml
hooks:
  post-start:
    - exec: 'platform self:update -qy'
```

I added this to my project.

**Comment by hanoii** [comment]
```yml
hooks:
  post-start:
    - exec: 'platform self:update -qy || true'
```
probably best

**Comment by lolautruche** [comment]
Hello
I agree, best would probably be to do this during `post-start` like @hanoii is suggesting.
Anyway, this will soon change with the Platform CLI v4 as we'll distribute it in a different way (apt, brew...)
