### ISSUE TITLE
README: Document how to add PLATFORMSH_CLI_TOKEN env var to use the cli

### ISSUE THREAD

**Issue by hanoii** [platformsh/ddev-platformsh#32]
Unless there's some fancy way of making `ddev platform login` work, I'd say the best way is using a token:

https://docs.platform.sh/administration/cli/api-tokens.html

There are different ways of doing it, env var right now seems to work just fine:

You can have a `config.platformsh.yaml` file that you won't commit with:

``` yml
web_environment:
  - PLATFORMSH_CLI_TOKEN=<YOUR_TOKEN>
```

Sorry I am not getting right into a PR, can't right now, but thought of at least sharing this.

**Comment by rfay** [comment]
It already does all that here... And it does it with a config.platformsh.yaml...

**Comment by hanoii** [comment]
ha, sorry, didn't see the install file.
