### ISSUE TITLE
PLATFORMSH_CLI_TOKEN will likely end up being committed and `config.platform.sh` won't but should

### ISSUE THREAD

**Issue by hanoii** [platformsh/ddev-platformsh#39]
Follow up to #32. If I am not mistaken, the `PLATFORMSH_CLI_TOKEN` will end up in `config.yaml` which will likely trigger a commit with it.

On #32 you said it was a `config.platform.sh` being created, but you are adding a lot of useful things from `.platform.app.yaml` that very likely needs to be committed, so something to think about:

`git add -f .ddev/config.platformsh.yaml` on install? If so, `PLATFORMSH_CLI_TOKEN` should likely go elsewhere, `config.platormsh.private.yaml`?

**Comment by rfay** [comment]
I think the right way to do this is to change to `ddev config global`, not sure what harm that would do.

Thanks so much for your engagement with this add-on!

**Comment by hanoii** [comment]
Sure, I am just chipping in, not really using it to its full extent. As for me, I happen to use a number of different platform cli tokens so I like the per project configuration of it. I may or may not be too common, in which case a global config that one can override per project should be just as good.
