### ISSUE TITLE
Add `PLATFORMSH_CLI_UPDATES_CHECK=0` somewhere as we are always updating cli on post-start hook.

### ISSUE THREAD

**Issue by hanoii** [platformsh/ddev-platformsh#40]
I was going to add it to the Dockerfile, but this should probably go into `config.platformsh.yaml` and while I was going to try a quick edit, I think #39 needs to be addressed first.

**Comment by rfay** [comment]
I think @lolautruche actually wants perpetual update; I'm not much of a fan of that.

**Comment by hanoii** [comment]
But you are doing the update on post-start, so it's kind of perpetual. With this you are saving some polling and the a possible update while you are working.

**Comment by rfay** [comment]
Yes, I moved it because of your request. Please say what you'd want to do. My preference is to keep it in the Dockerfile and use this env.

**Comment by hanoii** [comment]
:) I like the `post-start` better. What I am saying is that now that you are updating it in the post-start (thus, very frequently), it makes it more logical to add the env var at this time. Not saying to revert the other bit.

**Comment by lolautruche** [comment]
Thanks @hanoii for your suggestion.
This will change in the near future with the new CLI in Go, which won't be able to auto-update (it will be installed/updated using APT or binary direct download)

**Comment by rfay** [comment]
* https://github.com/drud/ddev/pull/4442
