### ISSUE TITLE
Improve actual support for PLATFORM_ROUTES

### ISSUE THREAD

**Issue by gilzow** [platformsh/ddev-platformsh#47]
List of php-based templates that in some way use/depend on PLATFORM_ROUTES

- [wordpress-bedrock](https://github.com/platformsh-templates/wordpress-bedrock/blob/master/.environment#L7)
- [wordpress-vanilla](https://github.com/platformsh-templates/wordpress-vanilla/blob/master/.environment#L7)
- [wordpress-woocommerce](https://github.com/platformsh-templates/wordpress-woocommerce/blob/master/.environment#L7)
- drupal8-multisite (both [directly](https://github.com/platformsh-templates/drupal8-multisite/blob/master/web/sites/default/drushrc.php#L6) and via psh config reader - [1](https://github.com/platformsh-templates/drupal8-multisite/blob/master/drush/platformsh_generate_drush_yml.php#L26), [2](https://github.com/platformsh-templates/drupal8-multisite/blob/master/web/sites/sites.php#L67))
- drupal9-multisite (both [directly](https://github.com/platformsh-templates/drupal9-multisite/blob/master/web/sites/default/drushrc.php#L6) and via psh config reader - [1](https://github.com/platformsh-templates/drupal9-multisite/blob/master/drush/platformsh_generate_drush_yml.php#L26), [2](https://github.com/platformsh-templates/drupal9-multisite/blob/master/web/sites/sites.php#L67))
- [magento2ce](https://github.com/platformsh-templates/magento2ce/blob/master/deploy.php#L40)
- [nextcloud](https://github.com/platformsh-templates/nextcloud/blob/master/_config/config.php#L2)
- laravel (via [laravel-bridge](https://github.com/platformsh/laravel-bridge/blob/master/platformsh-laravel-env.php#L90), via psh config reader)
- [typo3](https://github.com/platformsh-templates/typo3/blob/master/public/typo3conf/PlatformshConfiguration.php#L32) (via psh config reader)
- [wordpress-composer](https://github.com/platformsh-templates/wordpress-composer/blob/master/wp-config.php#L48) (via psh config reader)
- drupa8-govcms8 (via psh config reader - [1](https://github.com/platformsh-templates/drupal8-govcms8/blob/master/drush/platformsh_drush.inc#L22), [2](https://github.com/platformsh-templates/drupal8-govcms8/blob/master/drush/platformsh_generate_drush_yml.php#L26))
- drupa9-govcms9 (via psh config reader)
- [drupal8-opigno](https://github.com/platformsh-templates/drupal8-opigno/blob/master/drush/platformsh_generate_drush_yml.php#L26) (via psh config reader)
- [drupal8](https://github.com/platformsh-templates/drupal8/blob/master/drush/platformsh_generate_drush_yml.php#L26) (via psh config reader)
- [drupal9](https://github.com/platformsh-templates/drupal9/blob/master/drush/platformsh_generate_drush_yml.php#L26) (via psh config reader)
- ~pimcore (via psh config reader)~

**Comment by rfay** [comment]
Thanks so much!

**Comment by lolautruche** [comment]
Here is the documentation page about routes: https://docs.platform.sh/define-routes.html
However, it doesn't explain the properties in the JSON object (most notably the `original_url` property).

**Comment by gilzow** [comment]
just ran into an issue trying to use nextcloud which uses PLATFORM_ROUTES in [its config](https://github.com/platformsh-templates/nextcloud/blob/master/_config/config.php#L5). 

Currently in ddev, `$platform_sh_url` is set to `${DDEV_PRIMARY_URL}` which means the `explode` at line 6 produces only one key, so the attempt to grab key 1 results in passing `nul`l to `rtrim`, and then everything just falls apart after that.

**Comment by rfay** [comment]
@gilzow if from a template, can you link to the template please?

**Comment by lolautruche** [comment]
It's this one: https://github.com/platformsh-templates/nextcloud

Use of `$PLATFORM_ROUTES` is [here](https://github.com/platformsh-templates/nextcloud/blob/master/_config/config.php#L5).

**Comment by gilzow** [comment]
BTW, we're in the process of updating this template, hence why I'm working with it in DDEV.

For now I'm rebuilding the `PLATFORM_ROUTES` info with the DDEV reported URL hardcoded in `.ddev/config.platformsh.yaml` but we can't really ask developers to do that. 

DDEV has calculated and stored the generated URL in `.ddev/.ddev-docker-compose-full.yaml`. Is it possible to have the actual URL used when creating `PLATFORM_ROUTES` vs using the ${DDEV_PRIMARY_URL} variable?

**Comment by rfay** [comment]
Yes, it should use the actual URL. The question will be when there are many URLs of course.

**Comment by lolautruche** [comment]
@gilzow Can you please share what you're expecting to get (and that you set in `.ddev/config.platformsh.yaml`), vs what you're getting?

Thanks

**Comment by gilzow** [comment]
what i'm getting is 
```
{
  "${DDEV_PRIMARY_URL}": {
    "primary": true,
    "id": null,
    "production_url": "${DDEV_PRIMARY_URL}",
    "attributes": {},
    "upstream": "drupal",
    "type": "upstream",
    "original_url": "https://{default}/"
  }
}
```

What I'm expecting is:

```
{
  "https://nexcloud-upgrade-test.ddev.site/": {
    "primary": true,
    "id": null,
    "production_url": "https://nexcloud-upgrade-test.ddev.site/",
    "attributes": {},
    "upstream": "drupal",
    "type": "upstream",
    "original_url": "https://{default}/"
  }
}
```
### !!! IMPORTANT SIDE NOTE  !!!
please notice the inclusion of the trailing end slash (`/`) in both the route key and the `production_url` property. According to [our docs](https://docs.platform.sh/define-routes.html#trailing-slashes),  all generated routes now have a trailing slash. I mention this because the current value of `${DDEV_PRIMARY_URL}` does *not* contain the trailing slash. 

What i set in `.ddev/config.platformsh.yaml` is the base64 encoded version of the above:

```
"- PLATFORM_ROUTES=eyJodHRwczovL25leGNsb3VkLXVwZ3JhZGUtdGVzdC5kZGV2LnNpdGUvIjp7InByaW1hcnkiOnRydWUsImlkIjpudWxsLCJwcm9kdWN0aW9uX3VybCI6Imh0dHBzOi8vbmV4Y2xvdWQtdXBncmFkZS10ZXN0LmRkZXYuc2l0ZS8iLCJhdHRyaWJ1dGVzIjp7fSwidXBzdHJlYW0iOiJkcnVwYWwiLCJ0eXBlIjoidXBzdHJlYW0iLCJvcmlnaW5hbF91cmwiOiJodHRwczovL3tkZWZhdWx0fS8ifX0K"
```

**Comment by rfay** [comment]
The trailing slash probably *won't* make a difference here, but we'll add it anyway!

**Comment by lolautruche** [comment]
@rfay Do you know why `${DDEV_PRIMARY_URL}` is not resolved?

**Comment by rfay** [comment]
Interesting, not sure the context it's being evaluated in. Looks like it's not even being processed by bash, because if it were even being evaluated, it would then be empty.

**Comment by lolautruche** [comment]
Could it be because of the [HEREDOC](https://github.com/platformsh/ddev-platformsh/blob/main/install.yaml#L126-L137)?

```
  platform_routes=$(cat <<-"ENDROUTES"
  {
  "${DDEV_PRIMARY_URL}": {
    "primary": true,
    "id": null,
    "production_url": "${DDEV_PRIMARY_URL}",
    "attributes": {},
    "upstream": "drupal",
    "type": "upstream",
    "original_url": "https://{default}/"  }
  }
  ENDROUTES
  )
```

**Comment by rfay** [comment]
Yes, it could. There's a right way and wrong way to do that. I think if you use `"ENDROUTES"` it doesn't evaluate and if you use `ENDROUTES` it does.

**Comment by gilzow** [comment]
> Interesting, not sure the context it's being evaluated in.

as for _where_ this is being evaluated, [from inside PHP](https://github.com/platformsh-templates/nextcloud/blob/master/_config/config.php#L2-L8) after accessing `$_ENV['PLATFORM_ROUTES']` and base64 decoding & json decoding.

**Comment by gilzow** [comment]
> The trailing slash probably won't make a difference here, but we'll add it anyway!

oh, yeah it won't make a difference in this scenario, but when I was manually changing the value I noticed it and wanted to make sure I mention it since it _will_ make a difference in other situations.

**Comment by rfay** [comment]
* https://github.com/platformsh/ddev-platformsh/pull/71

**Comment by gilzow** [comment]
@lolautruche 
> However, it doesn't explain the properties in the JSON object (most notably the original_url property).
`original_url` property is the route key defined in routes.yaml. (e.g. `https://{default}/`).

**Comment by rfay** [comment]
@gilzow is that OK or not?

**Comment by rfay** [comment]
I imagine in the future we'll want much more significant versions of PLATFORM_ROUTES?

```
$ echo $PLATFORM_ROUTES | base64 -d | jq
{
  "https://first.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "primary": false,
    "id": null,
    "production_url": "https://first.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "attributes": {},
    "type": "upstream",
    "upstream": "drupal",
    "original_url": "https://first.{default}/"
  },
  "https://second.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "primary": false,
    "id": null,
    "production_url": "https://second.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "attributes": {},
    "type": "upstream",
    "upstream": "drupal",
    "original_url": "https://second.{default}/"
  },
  "https://main.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "primary": true,
    "id": null,
    "production_url": "https://main.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "attributes": {},
    "type": "upstream",
    "upstream": "drupal",
    "original_url": "https://main.{default}/"
  },
  "https://main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "primary": false,
    "id": null,
    "production_url": "https://main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "attributes": {},
    "type": "redirect",
    "to": "https://main.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "original_url": "https://{default}/"
  },
  "http://first.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "original_url": "http://first.{default}/",
    "id": null,
    "primary": false,
    "type": "redirect",
    "to": "https://first.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "production_url": "http://first.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/"
  },
  "http://second.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "original_url": "http://second.{default}/",
    "id": null,
    "primary": false,
    "type": "redirect",
    "to": "https://second.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "production_url": "http://second.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/"
  },
  "http://main.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "original_url": "http://main.{default}/",
    "id": null,
    "primary": false,
    "type": "redirect",
    "to": "https://main.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "production_url": "http://main.main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/"
  },
  "http://main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/": {
    "original_url": "http://{default}/",
    "id": null,
    "primary": false,
    "type": "redirect",
    "to": "https://main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/",
    "production_url": "http://main-bvxea6i-ljeh5qxqywco6.ca-1.platformsh.site/"
  }
}
```

I'm certainly not understanding why there are 8 entries here for a 3-site multisite.
