### ISSUE TITLE
PLATFORM_RELATIONSHIPS not available after upgrading to 0.5.0

### ISSUE THREAD

**Issue by gilzow** [platformsh/ddev-platformsh#54]
This might be related to #53 , but the environmental variable `PLATFORM_RELATIONSHIPS` is not present in my ddev application container after upgrading to ddev-platformsh 0.5.0 and performing a `ddev restart`

```
gilzow@batcon-ddev-test-4-web:/var/www/html$ printenv | grep RELATIONSHIPS
gilzow@batcon-ddev-test-4-web:/var/www/html$ 
```
Other `PLATFORM_*` environmental variables (e.g. PLATFORM_ROUTES, PLATFORM_MOUNTS, PLATFORM_DIR, etc.) **are** present.

**Comment by gilzow** [comment]
I just tried installing ddev-platformsh on a project that has never been configured to use ddev. 
`ddev start` 
tells me that there isn't a project and instructs me to run `ddev config`
I run `ddev config` and answer the questions. 
Once it is complete, I run `ddev get platformsh/ddev-platformsh` and answer the questions.
I then run `ddev restart` per the instructions at the end of installing ddev-platformsh
After restarting, I do `ddev pull platform` to import the database.
I then do `ddev ssh` and once inside, do `printenv | grep RELATION` and again, no platform relationships.

**Comment by gilzow** [comment]
```
❯ ddev version
 ITEM             VALUE                                   
 DDEV version     v1.21.3                                 
 architecture     amd64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.3 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.3             
 docker           20.10.8                                 
 docker-compose   v2.10.2                                 
 docker-platform  docker-desktop                          
 mutagen          0.16.0                                  
 os               darwin                                  
 router           drud/ddev-router:v1.21.3                
 web              drud/ddev-webserver:v1.21.3  
 ```

**Comment by rfay** [comment]
I'll chase this, but it just seems to be something that doesn't work out right with wordpress-composer. Thanks so much for the careful testing and reporting!

(Note that in your test project *all* environment variables are missing. I assume that means there's an if/end clause that has the wrong setup)
