### ISSUE TITLE
'ddev pull platform' not working when using multiple databases

### ISSUE THREAD

**Issue by Bart-St** [platformsh/ddev-platformsh#59]
Using a Drupal 9 multisite with two databases.
When executing the command: 'ddev pull platform' it encounters multiple relationships and stops.
It askes for a --relationship flag but the ddev command doesn't recognise it. 

ddev pull platform
You're about to delete the current database and files and replace with the results of a fresh pull.
Would you like to continue? [Y/n] (yes): yes
Authenticating...
Obtaining database...
More than one relationship found.
Use the --relationship (-r) option to specify a relationship. Options:

**Comment by rfay** [comment]
Thanks for trying it out, and thanks for reporting this! 

There isn't actually a plan to support multisite or multiple databases in the immediate future. 

Note that `ddev pull platform` is actually implemented in ddev itself, and obviously needs some more work to support this.

**Comment by rfay** [comment]
@Bart-St this is ready for review in 
* https://github.com/drud/ddev/pull/4426

would love it if you could give it a test.

Note that it does *not* work with the ddev-platformsh add-on, which gets confused about multiple databases.

**Comment by Bart-St** [comment]
Wow great! Tnx! 
I will give it a try this week. Will report the progress
