### ISSUE TITLE
Feature request: Add support for PLATFORM_CACHE_DIR environment variable

### ISSUE THREAD

**Issue by gilzow** [platformsh/ddev-platformsh#69]
I've come across a couple of projects that rely on the [PLATFORM_CACHE_DIR environmental variable ](https://docs.platform.sh/development/variables/use-variables.html#use-platformsh-provided-variables)and fail to install correctly when using DDEV with this add-on. 

Would it be possible to add this env var to the default mappings? For now I'm manually adding it into `./.ddev/config.platforsh.yaml` and restarting, but having it by default would be appreciated. Thanks!

**Comment by rfay** [comment]
Thanks! Are there templates you're using that demonstrate the problem?

**Comment by gilzow** [comment]
NextCloud and Pimcore are the two off the top of my head. NextCloud is the one I'm working on now that spawned this feature request.  

* [Nextcloud](https://github.com/platformsh-templates/nextcloud/blob/master/download-nextcloud.sh#L30)
* [Pimcore](https://github.com/platformsh-templates/pimcore/blob/master/install-redis.sh#L5)

The updated Pimcore template will [rely on it ](https://github.com/gilzow/pimcore-10.5/blob/main/.platform.app.yaml#L115)pretty heavily. 

And anyone who installs extras via our [homebrew instructions](https://community.platform.sh/t/can-i-use-homebrew/667/4) will need it.

**Comment by lolautruche** [comment]
Hi @gilzow and thanks for the report!
Can you please share the value you're currently setting manually in `.ddev/config.platformsh.yaml`?

**Comment by gilzow** [comment]
Normally I set it to the same as the system's `$TMPDIR` but in DDEV's case, that value isn't set. For this project I just set it to `/tmp`

```
- "PLATFORM_CACHE_DIR=/tmp"
```

**Comment by rfay** [comment]
* https://github.com/platformsh/ddev-platformsh/pull/72
