### ISSUE TITLE
Initial mapping from `.platform.app.yaml`

### ISSUE THREAD

**Issue by lolautruche** [platformsh/ddev-platformsh#7]
Read basic settings from[`.platform.app.yaml`](https://docs.platform.sh/create-apps/app-reference.html) and reflect them into `config.platformsh.yaml`

* Project name
* [PHP version from type](https://docs.platform.sh/create-apps/app-reference.html#types)
* [PHP extensions from runtime](https://docs.platform.sh/create-apps/app-reference.html#runtime)
* [Env variables](https://docs.platform.sh/create-apps/app-reference.html#variables) (basic ones including [basic `$PLATFORM_` ones](https://docs.platform.sh/development/variables/use-variables.html#use-platformsh-provided-variables)))
* [Mount Names](https://docs.platform.sh/create-apps/app-reference.html#mounts)

**Comment by rfay** [comment]
This really has to read both .platform.app.yaml + .platform/services.yaml right? They're like a poor-man's relational database?

**Comment by lolautruche** [comment]
It would be awesome if DDEV could benefit this improvement 🙂 .
In the meantime, I think we could only ensure that directories listed in _mounts_ exist locally, so that the app doesn't fail using files in those. Also, this would ensure that `ddev pull` doesn't fail on mounts.

**Comment by lolautruche** [comment]
Platform.sh containers are readonly. However, it is possible to create r/w capable "mounts" within containers for directories that need write access (e.g., logs, uploads, cache, etc).
What's important here is that we ensure those directories do exist.

For example:

```yaml
mounts:
    'web/uploads':
        source: local
        source_path: uploads
```

* `web/uploads` is the "name" of the mount, i.e. the writeable directory. It's the path in the app container, relative to the docroot.
* `source`: can only be "local". We can ignore
* `source_path`: the path in the external mounted drive. We can ignore it as well.

The only important part in this example is the "name" (`web/uploads`). We need to ensure the directory actually exists, and to create it if needed on start.

**Comment by rfay** [comment]
I think this is complete. Closing, followups in separate issues.
